name: Build, test and push image

concurrency: ${{ github.ref }}

on:
  push:
    branches:
      - main

jobs:
  build-test-image:
    uses: portswigger-apps/shared-workflows/.github/workflows/build-test-image.yaml@main
    secrets: inherit
    with:
      setup-go: true
