name: build-push-image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: "**/*.sum"

    - name: Build Go app
      run: |
        #!/bin/bash
        export GOOS="linux"
        cd cmd/moroz

        for GOARCH in "amd64" "arm64"
        do
          export GOARCH="${GOARCH}"
          mkdir -p build/${GOOS}/${GOARCH}
          go build -o ../../build/${GOOS}/${GOARCH}/moroz .
        done

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: docker-meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/portswigger-it/moroz:latest

    - name: Build multiarch Image and push to ghcr.io
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        push: true
        tags: ghcr.io/portswigger-it/moroz:latest
