name: build-push-image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build the Go application
      run: |
        mkdir -p build/linux
        cd cmd/moroz
        GOOS=linux GOARCH=arm go build -o ../../build/linux/moroz .

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build ARM64 Image and push to ghcr.io
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ghcr.io/portswigger-it/moroz:latest

    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
        exit-code: 1
        ignore-unfixed: true
        vuln-type: "os,library"
        severity: "CRITICAL"

    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

