name: renovate
on:
  workflow_dispatch: {}
  schedule:
  - cron: '30 8 * * 1'

jobs:
  renovate:
    uses: portswigger-cloud/github-actions/.github/workflows/shared-renovate.yaml@main
    secrets:
      RENOVATE_APP_ID: ${{ secrets.RENOVATE_APP_ID }}
      RENOVATE_APP_PEM: ${{ secrets.RENOVATE_APP_PEM }}
  
  post-to-a-slack-channel-on-failure:
    if: ${{ failure() }}
    uses: portswigger-cloud/github-actions/.github/workflows/shared-on-fail-slack-notifier.yaml@main
    needs: renovate
    secrets: inherit
